version: "3"


services:


  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_ORG=router 
      - DOCKER_INFLUXDB_INIT_BUCKET=syslog 
      - DOCKER_INFLUXDB_INIT_RETENTION=1w 
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=a_random_big_token_for_inital_setup
    volumes:
      - /logserver/influx/data:/var/lib/influxdb2 # Configuration directory
      - /logserver/influx/config:/etc/influxdb2     
    ports:
      - 8086:8086
    restart: unless-stopped


  telegraf:
    image: telegraf
    container_name: telegraf
    links:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./telegraf:/etc/telegraf/
    restart: unless-stopped  



  syslog-ng:
    image: lscr.io/linuxserver/syslog-ng:latest
    container_name: syslog-ng
    environment:
      - TZ=Europe/Rome
    links:
      - telegraf  
    volumes:
      - ./syslog/config:/config
      - /logserver/syslog/log:/var/log #optional
    ports:
      - 514:5514/udp
    restart: unless-stopped 



    
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    user: "0:0"
    volumes:
      - /logserver/grafana:/var/lib/grafana
    links:
      - influxdb   
    ports:
      - 3000:3000
    restart: unless-stopped  